name: ModelOps (Build, Deploy)
# Requires GitHub Action Secrets:
#   AZURE_WEBAPP_NAME
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# Hinweis:
#   Deine Web App sollte eine App-Einstellung AZURE_STORAGE_CONNECTION_STRING besitzen,
#   damit dein Container im Betrieb das Modell aus dem Blob laden kann (z.B. via app.py)

on:
  # Manuelles Starten
  workflow_dispatch:

  # Automatischer Trigger NACH erfolgreichem Modell-Update
  workflow_run:
    workflows: ["ModelOps (Update Model)"]
    types:
      - completed

permissions:
  packages: write      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
          file: ./Dockerfile    

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:latest'