name: ModelOps (Update Model)
# Requires GitHub Action Secrets: 
#   AZURE_STORAGE_CONNECTION_STRING 
#   MONGO_URI

on:
  # Automatischer Trigger bei Push auf den main-Branch
  push:
    branches:
      - main

  # Manuelles Starten
  workflow_dispatch:

jobs:
  model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Scrape + Store in Mongo
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          cd immo_spider
          scrapy crawl immoscout_spider -s CLOSESPIDER_PAGECOUNT=50
          cd ..

      - name: Train Model
        run: |
          cd model
          python model.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Upload Model to Azure Blob
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          cd model
          python save.py -c "${AZURE_STORAGE_CONNECTION_STRING}"